karllark/measure_extinction

measure_extinction/extdata.py
measure_extinction/stardata.py
measure_extinction/utils/make_obsdata_from_model.py
measure_extinction/utils/spex_corr.py

Hi,
I wrote code to calculate the scaling factor for the SpeX spectra, based on JHK photometry. It is calculating the mean of the 3 factors, and writing it to the .dat file. If there is already a spex correction factor in the .dat file, it will be overwritten. The way in which I coded the latter looks a bit cumbersome to me, so let me know if you have an idea to make this part better.
The "NaN" problem in the sum is not a problem anymore as StarData automatically replaces NaN values in the spectrum by 0s when reading in the spectrum.
I will add more stuff to do the scaling of the SXD and LXD separately, but need to "split" the spectra first.
Any suggestions/corrections are very welcome!
Marjorie

Scale SpeX spectra

---

measure_extinction/merge_obsspec.py

There are three different LXD modes: LXD 1.9, 2.1 and 2.3. The LXD long (2.3) mode was already included. I added the LXD short mode (1.9) because part of the spectra were taken in this mode.

Added LXD short mode

---

measure_extinction/extdata.py

When saving an extinction curve to a FITS file, it is now also saving the R(V) and A(V) values, and the uncertainties on the fitted parameters.

Save results

---

docs/index.rst
measure_extinction/extdata.py

Adding `wavenum` option to plotting of extinction curves.  Plotting versus 1/lambda is standard for UV extinction curve work - so useful.
Also have fixed a couple of bugs in the AverageExtData function.

Add wavenum plot option

---

measure_extinction/extdata.py

I added options to save the R(V) and E(B-V) values and uncertainties to the fits file header, and to read this information from a fits file header. In the read function, there is now duplicate code, because I save the asymmetric uncertainties with names "_L" for lower and "_U" for upper uncertainty. The existing code has "P" for plus and "M" for minus in the names. We should figure out what names we want to use, as well as if we want to read in and keep the asymmetric uncertainties (new code) or "average" the asymmetric uncertainties to obtain just 1 uncertainty value (existing code). All this would probably be solved if the fitting results and column information were saved as Astropy Tables instead of using header keywords (see issue #77 ).

Save uncertainties

---

measure_extinction/extdata.py
measure_extinction/plotting/plot_ext.py
measure_extinction/plotting/plot_spec.py
measure_extinction/stardata.py
measure_extinction/tests/test_calc_ext.py
measure_extinction/utils/calc_ext.py
setup.cfg

Add the capability to deredden star data based on FM90+CCM89 parameters.  This supports Milky Way UV extinction curve work where dereddening the standards is needed and has been a common technique for many years (see https://ui.adsabs.harvard.edu/abs/1992AJ....104.1916C/abstract).   For the MW standards, the necessary dereddening info is saved in the dat files.
Also added entry-points (aka system wide aliases) for meplot_spec, meplot_ext, and mecalc_ext that correspond to running the plotting/plot_spec, plotting/plot_ext, and utils/calc_ext scripts.

Dereddening for standards

---

measure_extinction/extdata.py
measure_extinction/merge_obsspec.py
measure_extinction/plotting/plot_ext.py
measure_extinction/plotting/plot_spec.py
measure_extinction/stardata.py
measure_extinction/utils/merge_spex_spec.py

This PR contains several changes to the plotting of spectra and extinction curves:
- Changed default plotting settings
- Added option to exclude certain bands from plotting instead of all bands or no bands
Other changes:
- Quadratically added 1 percent uncertainty to the SpeX spectra
- Small updates to masked windows of SpeX spectra
Some changes will be in conflict with the latest merge from PR #66 , so we will have to fix the conflicts first.

Plot tweaks

---

measure_extinction/extdata.py
measure_extinction/plotting/plot_ext.py
measure_extinction/stardata.py

I changed the way the extinction curves are rebinned.
The original code:
- had a bug related to slicing, see the discussion in issue #87.
- was calculating the mean of the same number of neighboring data points for every "bin". For non-equally spaced wavelength grids, one could thus potentially be taking the mean of values that are very far away.
- returned a nan if any of the values in the bin was nan.
The new code:
- uses a number of equally wide bins and calculates the mean wavelength and mean extinction in every bin. A different number of data points will be used in every bin if the wavelength grid is not equally spaced. This ensure that in sparse regions, not too much binning is happening.
- bins the wavelengths and extinction values at the same time.
- skips nan extinction values …

Rebinning extinction curves

---

measure_extinction/extdata.py

Adds in the A(V) uncertainty to the calculation.  Does not usually change the A(lam)/A(V) uncs given the small fractional errors on A(V).  But better to be correct if at all possible.

Adding the A(V) unc to E(lam-V) to A(lam)/A(V) calculation

---

measure_extinction/utils/calc_ext.py

Small PR to make the naming of the average extinction curve a little more flexible.
This is to make the script compatible with scripts in the spex_nir_extinction repo.

Use flexible output name

---

measure_extinction/extdata.py

It is now possible to directly save 1/R(V) and its uncertainties in the header of extinction files.

Added a keyword for the inverse of R(V)

---

measure_extinction/extdata.py
measure_extinction/plotting/plot_ext.py
measure_extinction/tests/test_EbvAvRv.py
measure_extinction/tests/test_extdata.py
setup.cfg

The three extdata member functions calc_EBV, calc_AV, and calc_RV now return tuples with (value, unc).  Previously, they only returned a float with the value.  The uncertainties are now calculated in these member functions.  This means that all use of these dust column measurements throughout the code now assume a tuple.  This was already the case when reading/writing extdata from/to disk.  The code should now be more consistent.
Changes were needed elsewhere to support all column measurements as tuples.
Also fixes a recently introduced bug.  Closes #97.

Updating dust columns to always be tuples with uncertainties

---

docs/calc_extinction.rst
docs/code_capabilities.rst
docs/index.rst
measure_extinction/extdata.py
measure_extinction/plotting/plot_ext.py
measure_extinction/plotting/plot_spec.py
measure_extinction/stardata.py
measure_extinction/tests/test_plot_spec.py
measure_extinction/tests/test_rebin.py

Adds option to rebin to a specified constant spectral resolution for spectra and spectral extinction curves.  Documentation for the basic classes and capabilities including the rebinning included.
As part of the testing of the rebinning, some changes to the plotting scripts were made.  One change was to remove the forcing of all filenames to be lower case allowing for a wider range of filenames to be used.  Another was to switch from using the filenames to using the saved names of the reddened and comparison stars in the extinction FITS files.
Finally, the wavenum capability added previously in PR #81 did not fully work with the plotting scripts.  Updates were made to more fully support plotting versus 1/lambda.  The missing plotting capabilities were revealed during the rebin testing. …

Add rebinning to a constant resolution for spectra and extinction data

---

measure_extinction/extdata.py

While there were keywords for extinction curve plotting for labeling the plot, there were not used.  This PR means they now actually do what they were advertised to do.
Some formatting changes after running black.

enabling labels in extinction plotting

---

.readthedocs.yml
measure_extinction/tests/test_plot_ext.py
measure_extinction/utils/fit_model.py
measure_extinction/utils/merge_iue_spec.py

In the lnlike function, the observed data were scaled to an average of 1, but the uncertainties were not.  This caused very large chisqr values leading to the priors not being used.  This has been fixed by scaling the model to the observed data.  Works much better as one would expect!

fix lnlike

---

measure_extinction/extdata.py

Simple addition to allow for B3 instead of C3 in the FM90 fits.  Change provided by FM90_B3 model in dust_extinction.

including B3 for FM90_B3 fit

---

measure_extinction/extdata.py
measure_extinction/merge_obsspec.py
measure_extinction/modeldata.py
measure_extinction/stardata.py
measure_extinction/utils/merge_miri_ifu_spec.py
measure_extinction/utils/merge_nircam_spec.py
measure_extinction/utils/merge_stis_spec.py
measure_extinction/utils/plot_mspec.py

Finalize NIRCam slitless capabilities.  Both observed and mocked spectra.
Adding keyword to only read in certain bands (useful for SED modeling).
Adding in new STIS filenaming convention.
Other minor improvements.

Finalize NIRCam spectra support, updates for STIS, etc.

---

docs/index.rst
measure_extinction/plotting/plot_spec.py
measure_extinction/stardata.py
measure_extinction/utils/fit_model.py
measure_extinction/utils/make_all_tlusty_obsdata.py
measure_extinction/utils/make_obsdata_from_model.py
measure_extinction/utils/merge_stis_spec.py

Adding Hubeny WD model grid.  Useful for absolute flux calibration work and, possibly, measuring local dust extinction at low dust columns.
Also fix a bug in reading in the Spitzer LRS model spectra - Jy units not correct.  May cause issue with real data - will fix when that happens.
Also fix a doc bug on astropy dev docs.

Add WD Hubeny models

---

measure_extinction/modeldata.py
measure_extinction/utils/fit_model.py

The full pull request includes two commits. 
The first commit adds an argument to `dust_extinguished_sed()` function in `model_data.py:212`, to take in a keyword that allows the sed to only be fit with `G23()`. 
`dust_extinguished_sed()` is called by `lnlike()` in `fit_model.py:88`, which in turn is called by `lnprob()` in `fit_model.py:151`
both `lnlike()` and `lnprob()` are updated to take in the new keyword "g23" as an optional argument. These were made optional arguments as not to break anything that continues to use these functions without the new argument. The default keyword is set to "all", which executes the original sed fitting in `dust_extinguished_sed()`, rather than `G23` only. The original sed fitting, done using the `_curve_F99_method()` can be called by excluding the new …

Add option to fit sed with G23 only

---

measure_extinction/extdata.py

When one has optical spectroscopy, it is better to use 0.55 micron as the relative "band" for the elx measurement.  This PR enables using a spectral wavelength instead of a photometric band.

Use spectral wavelength for relative "band" 

---

measure_extinction/extdata.py
measure_extinction/tests/test_conv55.py

Functions to covert A(55) and R(55) to A(V) and R(V).  Based on Fitzpatrick et al. (2019).

adding conversion functions and tests

---

measure_extinction/modeldata.py

Now fitting for FM90_B3 instead of FM90 (using C3) is an option.

Fitting with B3

---

measure_extinction/modeldata.py
measure_extinction/stardata.py
measure_extinction/tests/test_extdata.py
measure_extinction/utils/fit_model.py
measure_extinction/utils/make_all_tlusty_obsdata.py
measure_extinction/utils/make_obsdata_from_model.py

Computed from the MODEL_FULL_LOWRES (R=100) spectrum. 
MODEL_FULL_LOWRES spectra required.  Bandpasses read in and used in dust_extinguished_sed modeldata member function.  
Corrected small bug in photometry computation.
Corrected bugs in StarData reading of spectra.
Corrected bug in determining the default width for Teff and logg for fitting.
Updated one test to use np.allclose instead of np.testing.asset_almost_equal (was failing with 1e-7 difference on Macs).
Closes #135.

Correctly compute reddened photometry

---

measure_extinction/model.py

Expand the check for `npts > 0` to also include a check for `nan`s or `inf`s in the observed data. Then set weights only for the observed data where there are no `nan`s or +/- `inf`s. The remainder of the weights will remain zero.

Set weight=0 for obsdata = nans or infs

---

measure_extinction/extdata.py

saving fit parameters as tables in extensions

---

measure_extinction/model.py

Use by setting resume=True in the model fit_sampler member function.
Fixes the save_backend bug when save_samples is not set.
Closes #148

can resume from previously saved chain

---

measure_extinction/extdata.py
measure_extinction/plotting/plot_ext.py

Makes sure the rel_band is either a string (for a band) or a astropy quantity (for a wavelength).  This allows the trans functions to do the right thing based on the header keywords.
Note that the header keywords still say AV = XX and EBV = XX even when it really is A55 and E4455.  Would be good to do a bit of an overhaul to have the header keywords more generic (e.g., AX and EYX) and have the X and Y  given in rel_band and a new keyword rel_band2 (or something like that).  This requires a bunch of changes to the code.  An issue opened for this #157.

Fix bugs when normalizing by A(55) or E(44-55)

---

measure_extinction/extdata.py
measure_extinction/merge_obsspec.py
measure_extinction/model.py
measure_extinction/plotting/plot_model.py
measure_extinction/tests/test_merge_obsspec.py
measure_extinction/utils/make_obsdata_from_model.py
measure_extinction/utils/merge_miri_ifu_spec.py
measure_extinction/utils/merge_nircam_spec.py

Adding in the two grating for WFC3 IR grism data.  
As part of this, simplified the merging of spectra and generation of mock spectra from models.

Add WFC3 grism mocking for models
