measure_extinction/merge_obsspec.py
measure_extinction/stardata.py
measure_extinction/utils/make_obsdata_from_model.py
measure_extinction/utils/merge_stis_spec.py
measure_extinction/utils/plot_spec.py

Next incremental improvement.  Includes making stis uv and optical mock observations.  And other needed improvements.

Model standards

---

docs/calc_extinction.rst

Thanks to Ralf S. for pointing out this typo.

Fix doc typo

---

measure_extinction/_astropy_init.py

This is an automated update made by the astropy package-template ``batchpr``
tool :robot: - feel free to close if it doesn't look good!
You can report issues to @bsipocz.

Package-template update: _astropy_init.py

---

.gitignore
.travis.yml
ah_bootstrap.py
docs/conf.py
licenses/LICENSE.rst
measure_extinction/conftest.py
measure_extinction/extdata.py
measure_extinction/merge_obsspec.py
measure_extinction/utils/__init__.py
measure_extinction/utils/merge_spex_spec.py
measure_extinction/utils/merge_stis_spec.py
setup.cfg

Hopefully will fix the travis failure on the coverage test

Update to latest package template and astropy-helpers

---

measure_extinction/utils/plot_bandpasses.py

This was just a little fix I did a while ago, but forgot to commit.

Extcurve plotting

---

measure_extinction/extdata.py

Needed to correctly compute the average of the photometry portion of the curve

fixing the creating of an average curve

---

measure_extinction/stardata.py

Allows for the two different types of stacked spectra plots - linear and log on the y-axis.

Added add/multiply options for yoffset in plotting

---

measure_extinction/stardata.py
measure_extinction/utils/plot_bandpasses.py
measure_extinction/utils/scale_spex_spec.py

I added the WISE bands to the possible bands. I updated the scaling function so that it uses WISE data when no IRAC data is available.

New photometry scaling

---

measure_extinction/extdata.py
measure_extinction/stardata.py

Add the ability to ignore IRSblue data

---

measure_extinction/utils/make_all_tlusty_obsdata.py

fix import error

---

docs/index.rst
measure_extinction/conftest.py
setup.cfg

Closes #56.
Also a few minor updates to address comments on PR #54.

Ignore docs on local

---

measure_extinction/extdata.py
measure_extinction/tests/test_extdata.py

Updates to include powerlaw + 2 asymmetric Drude fits for MIR extinction.  Includes a more generic save fit parameter code.  Minor updates to better handle column information.

Aug 2020 IR extinction motivated changes

---

measure_extinction/merge_obsspec.py
measure_extinction/utils/merge_spex_spec.py

I added the option to provide wavelength regions in the .dat files of the stars that need masking, e.g. because the data is completely off.

Mask bad regions in spex spectra

---

measure_extinction/extdata.py

Makes the model saving a bit more flexible (useful in the SMC extinction case where I do not [yet?] have access to the fit parameters).

Allow models to be saved w/o parameters specified

---

measure_extinction/plotting/plot_ext.py
measure_extinction/stardata.py

I added more flexibility to the plotting settings so that this repo is again compatible with the spex_nir_extinction repo, and can be used for future projects without having to change all the settings manually.

Add more flexibility to plotting settings

---

measure_extinction/merge_obsspec.py
measure_extinction/plotting/plot_ext.py

This small PR makes sure that the fitted extinction models will match the data when plotting in A(lambda)/A(V).

Plot fitted models in A(lambda)/A(V)

---

measure_extinction/conftest.py
measure_extinction/merge_obsspec.py
measure_extinction/modeldata.py
measure_extinction/plotting/plot_spec.py
measure_extinction/stardata.py
measure_extinction/tests/test_rebin.py
measure_extinction/tests/test_stardata.py
measure_extinction/utils/calc_ext.py
measure_extinction/utils/make_all_tlusty_obsdata.py
measure_extinction/utils/make_obsdata_from_model.py
measure_extinction/utils/merge_iue_spec.py
measure_extinction/utils/merge_stis_spec.py
measure_extinction/utils/plot_bandpasses.py
measure_extinction/utils/plot_mspec.py

black all code

---

measure_extinction/extdata.py

Enhance extinction curve averaging

---

measure_extinction/modeldata.py
measure_extinction/stardata.py
measure_extinction/utils/fit_model.py

updating to normalize to all the data

---

measure_extinction/stardata.py
measure_extinction/utils/merge_stis_spec.py

This PR contains 3 commits in total, as listed below. 
1. syntax correction from `np.NaN` to `np.nan`
2. introduce a new input parameter in function `StarData` to read star data called `only_data`. This input parameter takes in the dataname i.e. "STIS", "STIS_Opt", etc and only reads this data.
3. store the merged star data file written by merge_stis_spec.py in the filepath given to the argument `outpath`.

Separate stellar param fitting by wavelength region

---

measure_extinction/extdata.py
measure_extinction/model.py
measure_extinction/modeldata.py
measure_extinction/plotting/plot_ext.py
measure_extinction/plotting/plot_spec.py
measure_extinction/stardata.py

General tidying and making this better.

Usability updates

---

measure_extinction/extdata.py
measure_extinction/model.py
measure_extinction/plotting/plot_ext.py
measure_extinction/utils/merge_stis_spec.py

Add Ly-alpha plots

---

measure_extinction/stardata.py
measure_extinction/utils/make_all_tlusty_obsdata.py
measure_extinction/utils/make_obsdata_from_model.py
measure_extinction/utils/make_tlusty_all

Continuum useful for making plots highlighting the lines (data / best fit model continuum).
Individual STIS low-res gratings mocked to allow for expansion of fitting to allow for small shifts independent for each grating.

Mocking of continuum and output of individual stis gratings
